const { chromium, URL_APP } = require('./_socle.cjs');
let ok=0,ko=0; const T=(n,c,d)=>{ if(c){ok++;console.log('  ✓ '+n);} else {ko++;console.log('  ✗ '+n+' — '+(d||''));} };
(async()=>{ const b=await chromium.launch(); const p=await b.newPage({viewport:{width:1500,height:1000}}); const errs=[]; p.on('pageerror',e=>{ if(!/ServiceWorker/.test(e.message)) errs.push(e.message.slice(0,200)); }); p.on('dialog',d=>d.accept());
await p.goto(URL_APP); await p.waitForTimeout(900);
await p.evaluate(()=>{ if(typeof _authGranted==='function')_authGranted(); }); await p.waitForTimeout(2000);
const ev=(f,a)=>p.evaluate(f,a);
await ev(()=>{ window.__toasts=[]; const _t=window.toast; window.toast=function(m){ window.__toasts.push(''+m); try{ return _t&&_t.apply(this,arguments); }catch(e){} };
  const D=86400000, now=Date.now(); DB.parametres=DB.parametres||{};
  DB.parametres.prevoyance={journal:[{ts:now-3600000,step:'Analyse',ok:true,detail:'Prévoyance : 3 point(s)',mode:'automatique'}],vus:{},snooze:{},seen:{},sources:{}};
  DB.parametres.cfChaine={journal:[{ts:now-2*D,step:'Mensualités',ok:true,detail:'2 générées',mode:'manuel',qui:'Karim'},{ts:now-40*D,step:'Relances',ok:false,detail:'passerelle indisponible',mode:'automatique'}]};
  DB.parametres.factPresta={chaine:{journal:[{ts:now-5*D,step:'Relève',ok:true,detail:'4 factures',mode:'automatique'}]}};
  DB.parametres.incidents=[{ts:now-D,titre:'Fenêtre bloquée',detail:'pop-up',kind:'popup',page:'editions'}];
  DB.parametres.partagesLien=[{ts:now-6*D,canal:'e-mail',dest:'amelie@outlook.fr',url:'https://marq.aemconseil.eu/depot.html?d=DOS-2026-000777&k=abc',numero:'DOS-2026-000777'},{ts:now-1*D,canal:'SMS',dest:'+33612345678',url:'https://marq.aemconseil.eu/depot.html?d=DOS-2026-000777&k=abc',numero:'DOS-2026-000777',relance:true}];
  DB.parametres.liensSuivi={journal:[{ts:now-1*D,numero:'DOS-2026-000777',type:'depot',to:'+33612345678',ok:true,mode:'automatique',canal:'SMS',detail:''}]};
  /* v703 : le registre des numéros tient son propre journal — mis à zéro pour garder la ligne de base à 10 entrées */
  DB.parametres.numeros={attribues:{},journal:[]};
  DB.clients=[{id:'c1',nom:'Bernard',prenom:'Amélie',email:'amelie@outlook.fr'}]; DB.demandes=[{id:'dq1',clientNom:'Paul Martin',numeroDossier:'DOS-2026-000888',statut:'Nouveau',date:'2026-09-01',historique:[{d:new Date(now-8*D).toISOString().slice(0,10),t:'Fiche pré-remplie depuis le questionnaire du site'}]}];
  DB.dossiers=[{id:'do-t',ref:'DOS-2026-000777',clientIds:['c1'],serviceIds:[],statut:'Pièces attendues',createdAt:'2026-09-01',historique:[{d:new Date(now-2*D).toISOString().slice(0,10),t:'Statuts signés reçus'}]}];
  state.page='params'; render(); });
await p.waitForTimeout(400);
let w=await ev(()=>{ const L=auditEntrees(); const srcs={}; L.forEach(o=>srcs[o.srcLbl]=(srcs[o.srcLbl]||0)+1); const first=L[0]; const desc=L.every((o,i)=>i===0||L[i-1].ts>=o.ts); return {n:L.length,srcs,firstAction:first&&first.action,desc,card:!!document.querySelector('.au-card'),sub:(document.querySelector('.au-card .sub')||{}).textContent}; });
T('Collecte : 10 entrées (Prévoyance, Fiscal ×2, Factures prestataires, Incidents, Liens envoyés ×2, Rappels de liens, Dossiers, Demandes), tri décroissant, carte présente « 10 entrées · 2 échecs »', w.n===10&&w.srcs['Prévoyance']===1&&w.srcs['Fiscal']===2&&w.srcs['Factures prestataires']===1&&w.srcs['Incidents']===1&&w.srcs['Liens envoyés']===2&&w.srcs['Rappels de liens']===1&&w.srcs['Dossiers']===1&&w.srcs['Demandes']===1&&w.desc&&w.card&&/10 entrées/.test(w.sub)&&/2 échecs/.test(w.sub), JSON.stringify(w));
w=await ev(()=>({rows:document.querySelectorAll('.au-tbl tbody tr').length,ko:document.querySelectorAll('.au-tbl tbody tr.au-ko').length,txt:document.querySelector('.au-tbl').innerText}));
T('Affichage 30 jours par défaut : 9 lignes (la relance fiscale de 40 j exclue), 1 ligne en échec (incident), détails visibles', w.rows===9&&w.ko===1&&/Fenêtre bloquée/.test(w.txt)&&/Statuts signés reçus/.test(w.txt)&&/rappel · dépôt de pièces · SMS/.test(w.txt)&&/DOS-2026-000777 · Amélie Bernard/.test(w.txt), JSON.stringify({rows:w.rows,ko:w.ko}));
await ev(()=>auditFiltre('per','0')); w=await ev(()=>document.querySelectorAll('.au-tbl tbody tr').length);
T('Période « Tout » → 10 lignes', w===10, 'n='+w);
await ev(()=>auditFiltre('ko',true)); w=await ev(()=>[...document.querySelectorAll('.au-tbl tbody tr')].map(tr=>tr.children[1].textContent));
T('Échecs seulement → Fiscal (relances) + Incidents', w.length===2&&w.indexOf('Fiscal')>=0&&w.indexOf('Incidents')>=0, JSON.stringify(w));
await ev(()=>{ auditFiltre('ko',false); auditFiltre('src','cfChaine'); }); w=await ev(()=>document.querySelectorAll('.au-tbl tbody tr').length);
T('Filtre source Fiscal → 2 lignes', w===2, 'n='+w);
await ev(()=>{ auditFiltre('src',''); auditFiltre('q','DOS-2026-000888'); }); w=await ev(()=>[...document.querySelectorAll('.au-tbl tbody tr')].map(tr=>tr.children[4].textContent));
T('Recherche « DOS-2026-000888 » → la demande de Paul Martin', w.length===1&&/Paul Martin/.test(w[0]), JSON.stringify(w));
await ev(()=>auditFiltre('q',''));
// exports
w=await ev(async()=>{ let blobs=[]; const _c=URL.createObjectURL; URL.createObjectURL=function(bl){ blobs.push(bl); return 'blob:x'; }; auditExport('csv'); auditExport('json'); URL.createObjectURL=_c; const csv=await blobs[0].text(); const js=JSON.parse(await blobs[1].text()); return {csvHead:csv.split('\n')[0],csvLines:csv.trim().split('\n').length,type:js.type,ver:js.version,verOk:js.version===LAST_VER,nb:js.nb,entrees:js.entrees.length,raw:Object.keys(js.journauxBruts),e0:js.entrees[0]}; });
T('Export CSV (en-tête + 10 lignes) et fichier d\'audit JSON unique (type marq-audit, version, 10 entrées, journaux bruts prévoyance/cfChaine/factPresta.chaine/liensSuivi/incidents/partagesLien)', /^﻿?Date;Source;Action;État;Détail;Référence;Par$/.test(w.csvHead)&&w.csvLines===11&&w.type==='marq-audit'&&w.verOk&&w.nb===10&&w.entrees===10&&['prevoyance','cfChaine','factPresta.chaine','liensSuivi','incidents','partagesLien','numeros'].every(k=>w.raw.indexOf(k)>=0)&&w.e0&&w.e0.etat, JSON.stringify({head:w.csvHead,lines:w.csvLines,ver:w.ver,raw:w.raw}));
// état vide
w=await ev(()=>{ DB.parametres.prevoyance.journal=[]; DB.parametres.cfChaine.journal=[]; DB.parametres.factPresta.chaine.journal=[]; DB.parametres.incidents=[]; DB.parametres.partagesLien=[]; DB.parametres.liensSuivi.journal=[]; DB.parametres.numeros.journal=[]; DB.dossiers[0].historique=[]; DB.demandes[0].historique=[]; render(); return {n:auditEntrees().length,empty:!!document.querySelector('.au-card .au-empty')}; });
T('Sans aucun journal : état vide explicite', w.n===0&&w.empty, JSON.stringify(w));
await ev(()=>{ const now=Date.now(), D=86400000; DB.parametres.prevoyance.journal=[{ts:now-3600000,step:'Analyse',ok:true,detail:'Prévoyance : 3 point(s)',mode:'automatique'}]; DB.parametres.cfChaine.journal=[{ts:now-2*D,step:'Mensualités',ok:true,detail:'2 générées',mode:'manuel',qui:'Karim'},{ts:now-3*D,step:'Relances',ok:false,detail:'passerelle indisponible',mode:'automatique'}]; DB.parametres.incidents=[{ts:now-D,titre:'Fenêtre bloquée',detail:'pop-up',kind:'popup',page:'editions'}]; DB.parametres.partagesLien=[{ts:now-6*D,canal:'e-mail',dest:'amelie@outlook.fr',url:'https://marq.aemconseil.eu/depot.html?d=DOS-2026-000777&k=abc',numero:'DOS-2026-000777'}]; DB.dossiers[0].historique=[{d:new Date(now-2*D).toISOString().slice(0,10),t:'Statuts signés reçus'}]; render(); });
await p.waitForTimeout(300); w=await ev(()=>{ try{ spGo('sec/audit',0); }catch(e){} const s=document.querySelector('.sp-slot[data-slot="sec/audit"]'); return {slot:!!s,on:!!(s&&s.classList.contains('on')),card:!!(s&&s.querySelector('.au-card')),nav:!!document.querySelector('.sp-item[data-p="sec/audit"]')}; }); T('Carte rangée dans Paramètres › Sécurité › Journal d\'activité (entrée de navigation, slot actif)', w.slot&&w.on&&w.card&&w.nav, JSON.stringify(w)); await p.waitForTimeout(300); await p.screenshot({path:'v685-audit.png'});
T('0 erreur de page', errs.length===0, errs.join(' | '));
console.log('TOTAL', ok, 'ok /', ko, 'ko'); await b.close(); process.exit(ko?1:0); })();
