const { chromium, URL_APP } = require('./_socle.cjs');
let ok=0,ko=0; const T=(n,c,d)=>{ if(c){ok++;console.log('  ✓ '+n);} else {ko++;console.log('  ✗ '+n+' — '+(d||''));} };
(async()=>{ const b=await chromium.launch(); const p=await b.newPage({viewport:{width:1500,height:1100}}); const errs=[]; p.on('pageerror',e=>{ if(!/ServiceWorker/.test(e.message)) errs.push(e.message.slice(0,200)); }); p.on('dialog',d=>d.accept());
await p.goto(URL_APP); await p.waitForTimeout(900);
await p.evaluate(()=>{ if(typeof _authGranted==='function')_authGranted(); }); await p.waitForTimeout(1800);
const ev=(f,a)=>p.evaluate(f,a);
const d=(n)=>{ const x=new Date(); x.setDate(x.getDate()+n); return x.toISOString().slice(0,10); };
const ym=new Date().toISOString().slice(0,7);
await ev(({d1,p20,p45,ym})=>{ window.uiConfirm=(m,fn)=>fn&&fn(); window.confirm=()=>true; window.alert=()=>{}; window.__toasts=[]; const _t=window.toast; window.toast=function(m){ window.__toasts.push(''+m); try{ return _t&&_t.apply(this,arguments); }catch(e){} }; window.__opens=[]; window.open=(u)=>{ window.__opens.push(''+u); return {close(){},focus(){},document:{write(){},close(){}},print(){}}; }; window.__dls=[]; HTMLAnchorElement.prototype.click=function(){ window.__dls.push(this.download||''); }; window.__sent=[]; window.demSendViaScript=function(to,s,b,cb,o){ window.__sent.push({to,s}); if(typeof cb==='function') setTimeout(function(){ cb(true); },0); return true; };
  try{ ['demandes','agenda','fiscal','conformite'].forEach(id=>{ try{ modPauseSet(id,false); }catch(e){} }); }catch(e){}
  DB.parametres.mailSync={url:'https://script.example/exec',key:'k'}; window.fetch=function(){ return Promise.resolve({text:()=>Promise.resolve('{}')}); };
  ['factChaine','agChaine','cfChaine','cliChaine','ydChaine','tvrChaine','jcChaine','cxChaine'].forEach(k=>{ DB.parametres[k]=null; });
  DB.clients=[{id:'c1',clientType:'entreprise',denomination:'LOGIS PICARDIE',prenom:'Sophie',nom:'LAMBERT',forme:'SAS',siren:'912456789',adresse:'14 rue des Jacobins',cp:'80000',ville:'Amiens',president:'Sophie LAMBERT',email:'s@l.fr',tel:'0612345678'},{id:'c2',clientType:'entreprise',denomination:'DUPONT SARL',email:'eric@dupont.fr'}];
  DB.demandes=[{id:'q1',clientNom:'Marc LEROY',clientEmail:'marc@leroy.fr',date:new Date().toISOString(),intake:{type:'sasu',societe:{denomination:'LEROY CONSEIL',forme:'SASU'}},att:[]}];
  DB.dossiers=[{id:'d1',ref:'DOS-1',clientIds:['c1','c2'],statut:'Qualification',createdAt:'2026-09-01',wf:{},historique:[],intake:{type:'sas',societe:{denomination:'LOGIS PICARDIE'}}}];
  const hh=String(Math.min(23,new Date().getHours()+1)).padStart(2,'0')+':00';
  DB.parametres.rdv=[{id:'r1',date:d1,heure:hh,clientNom:'Sophie LAMBERT',objet:'Signature des statuts',type:'signature',statut:'prevu',lieu:'Bureau'},{id:'r3',date:d1,heure:hh,clientNom:'Inconnu',objet:'Sans e-mail',type:'appel',statut:'prevu'}];
  DB.abonnes=[{id:'a1',raison:'LOGIS PICARDIE',forme:'SAS',siren:'912456789',fiscal:'IS',tva:'mensuel',sal:'oui',dir:'assimile',clot:'12',aboFormule:'Essentiel',aboMensualite:150,abonnementActif:true,factures:[{id:'f1',numero:'AB-0001',type:'abonnement',libelle:'Abonnement',ht:150,tva:20,ttc:180,date:p45,echeance:p20,statut:'emise',relances:[]}],obligations:[]}];
  DB.parametres.facturier=[]; window.__invDraft=null; window.__invUI={tab:'new',hidePrev:false}; state.page='facturier'; render();
  invNouveauBrouillon(); invSetType('facture'); const dr=window.__invDraft; dr.clNom='LOGIS PICARDIE'; dr.clMail='s@l.fr'; dr.emNom='AEM CONSEIL'; dr.lignes=[{des:'Honoraires',qte:1,pu:500}]; dr.tva=20; render(); invSave('emise');
  DB.parametres.factPresta={list:[{id:'p1',fournisseur:'OVH',numero:'OV-1',dateFact:'2026-09-02',ht:'100.00',taux:'20',tva:'20.00',ttc:'120.00',compteCharge:'606100000',statut:'traitee'},{id:'p5',fournisseur:'GREFFE',numero:'G-1',dateFact:'2026-09-01',ht:'50.00',taux:'20',tva:'10.00',ttc:'60.00',compteCharge:'606100000',statut:'ecriture',ecritureLe:'2026-09-06T10:00:00Z'}],lastSync:new Date().toISOString()};
  DB.parametres.tvaFactures=[]; DB.facturesPrestataires=[]; DB.paie26={annees:{}};
  /* l'échéancier dépend du calendrier : on y pose un poste mensuel toujours
     dans la fenêtre de rappel, pour que le test ne dépende pas du jour */
  try{ const o=JSON.parse(localStorage.getItem('last-svc')||'{}'); o.eche=o.eche||{};
    o.eche.items=[{id:'ech-t',lbl:'Déclaration de TVA',actif:true,peri:'mensuel',day:15,rappel:31,dernier:''}];
    localStorage.setItem('last-svc',JSON.stringify(o)); }catch(e){}
  save(); state.page='cockpit'; render(); },{d1:d(1),p20:d(-20),p45:d(-45),ym});
await p.waitForTimeout(400);
let w=await ev(()=>{ const L=cxChaineLignes(); return {keys:L.map(l=>l.key).join(), att:L.map(l=>l.key+':'+l.attente+'/'+l.humain).join(), ex:L.filter(l=>l.exec).map(l=>l.key).join(), lbl:L.filter(l=>!l.exec).map(l=>l.key+'='+l.execLbl).join(), det:L.map(l=>l.key+'='+l.detail).join(' | ')}; });
T('Lignes : quatorze chaînes présentes (dont Questionnaire, Échéancier, Veille et Études) ; Demandes et Traitement en contrôle humain, Export YADA en téléchargement ; exécutables : Facturation, Agenda, Fiscal, Clients, Factures prestataires, Remboursement TVA, Justificatifs', w.keys==='dem,trw,fact,ag,cf,cli,fq,fp,yd,tvr,jc,ech,ve,em'&&w.ex==='fact,ag,cf,cli,fq,fp,tvr,jc,ech,ve'&&/dem=Contrôle humain/.test(w.lbl)&&/trw=Par dossier/.test(w.lbl)&&/yd=Fichier à télécharger/.test(w.lbl)&&/dem:1\/1/.test(w.att)&&/trw:1\//.test(w.att)&&/fp:2\/1/.test(w.att)&&/yd:2\/2/.test(w.att), JSON.stringify(w));
w=await ev(()=>{ const v=document.getElementById('view'); const c=v.querySelector('.cxc-card'); const t=c?c.innerText:''; const ck=v.querySelector('.ckp'); const kids=ck?Array.from(ck.children).map(x=>x.classList.contains('cxc-card')?'cxc-card':x.className.split(' ')[0]):[]; return {card:!!c, pos:kids.indexOf('cxc-card'), first:kids[0], rows:v.querySelectorAll('.cxc-row').length, execBtn:v.querySelectorAll('.cxc-row .btn-pri').length, open:v.querySelectorAll('.cxc-row .btn-ghost').length, tout:/Tout exécuter \(10\)/.test(t), sum:/en attente · .* action\(s\) humaine\(s\) · 10 chaîne\(s\) exécutable\(s\)/.test(t), u:(t.match(/undefined|NaN(?![a-zA-Z])|\[object Object\]/g)||[]).length, once:v.querySelectorAll('.cxc-card').length}; });
T('Panneau « Centre d\'exécution » sous l\'en-tête du Tableau de bord (page intacte, une seule carte) : 14 lignes, 10 boutons Exécuter, 14 boutons Ouvrir, « Tout exécuter (10) », résumé', w.card&&w.first==='ckp-head'&&w.pos===1&&w.rows===14&&w.execBtn===10&&w.open===14&&w.tout&&w.sum&&w.u===0&&w.once===1, JSON.stringify(w));
w=await ev(()=>{ window.__sent=[]; const r=cxChaineExecuter('fact'); const f=DB.parametres.facturier.find(x=>x.statut==='emise'); return {r, sent:window.__sent.length, to:(window.__sent[0]||{}).to, env:!!(f&&(f.envoyeLe||f.envoye||f.dateEnvoi)), j:DB.parametres.cxChaine.journal[0], toast:window.__toasts.slice(-1)[0], apres:cxChaineLignes().find(l=>l.key==='fact').exec===null}; });
T('Exécuter « Facturation » : la facture émise part par la passerelle (1 envoi), journal du centre, résumé, plus rien à exécuter pour ce module', /1 envoi/.test(''+w.r)&&w.sent===1&&w.to==='s@l.fr'&&/Facturation/.test(w.j.step)&&w.j.ok&&/Facturation : 1 envoi/.test(w.toast)&&w.apres, JSON.stringify(w));
w=await ev(()=>{ const r=cxChaineExecuter('dem'); return {r, toast:window.__toasts.slice(-1)[0], n:DB.parametres.cxChaine.journal.length}; });
T('Exécuter une chaîne à contrôle humain (Demandes) → refus explicite, rien journalisé', w.r===null&&/Rien à exécuter automatiquement/.test(w.toast)&&w.n===1, JSON.stringify(w));
w=await ev(()=>{ window.__sent=[]; window.__toasts=[]; const n=cxChaineTout(); const L=cxChaineLignes(); const fp=DB.parametres.factPresta.list; const jc=DB.facturesPrestataires; const tv=DB.parametres.tvaFactures; const a1=DB.abonnes[0]; return {n, sent:window.__sent.map(x=>x.to).sort().join(), fpSt:fp.map(f=>f.statut).join(), jc:jc.length, tv:tv.length, mens:a1.factures.filter(f=>(f.date||'').slice(0,7)===new Date().toISOString().slice(0,7)&&f.type==='abonnement').length, rest:L.filter(l=>l.exec).map(l=>l.key).join(), j:DB.parametres.cxChaine.journal[0], toast:window.__toasts.slice(-1)[0], jn:cxChaineJournal().length, mods:Array.from(new Set(cxChaineJournal().map(x=>x.mod))).sort().join()}; });
T('« Tout exécuter » : rappel d\'agenda + mensualité fiscale + demande d\'informations client (passerelle), écriture prestataire générée, 3 factures reprises pour la TVA, 2 paiements repris en justificatifs ; journal consolidé multi-modules ; plus rien d\'exécutable', w.n===9&&/s@l\.fr/.test(w.sent)&&/eric@dupont\.fr/.test(w.sent)&&/marc@leroy\.fr/.test(w.sent)&&/aemconseil\.sas@gmail\.com/.test(w.sent)&&w.fpSt==='ecriture,ecriture'&&w.jc===2&&w.tv===3&&w.mens===1&&/Tout exécuter/.test(w.j.step)&&/Agenda/.test(w.j.detail)&&/Fiscal/.test(w.j.detail)&&/Justificatifs/.test(w.j.detail)&&/Centre d.exécution/.test(w.toast)&&w.jn===10&&w.mods.split(',').length>=5, JSON.stringify(w));
await p.waitForTimeout(1200); w=await ev(()=>{ render(); const r=cxChaineTout(); const v=document.getElementById('view'); const t=(v.querySelector('.cxc-card')||{}).innerText||''; return {r, toast:window.__toasts.slice(-1)[0], dis:!!(Array.from(v.querySelectorAll('.cxc-hb .btn-pri'))[0]||{}).disabled, tout0:/Tout exécuter \(0\)/.test(t), last:/Facturation/.test(t)&&/Tout exécuter/.test(t)}; });
T('Second passage : plus rien d\'exécutable (bouton désactivé), dernières actions affichées par module', w.r===0&&/Aucune chaîne exécutable/.test(w.toast)&&w.dis&&w.tout0&&w.last, JSON.stringify(w));
w=await ev(()=>{ cxChaineToggle(); const r=!document.querySelector('#view .cxc-row')&&!!document.querySelector('#view .cxc-card'); cxChaineToggle(); const b=document.querySelector('#view .cxc-row .btn-ghost'); b&&b.click(); const pg=state.page; state.page='cockpit'; render(); return {reduit:r, pg, ser:(function(){ try{ JSON.stringify(DB); return true; }catch(e){ return false; } })()}; });
T('Panneau réductible, « Ouvrir » navigue vers le module (Demandes), base sérialisable', w.reduit&&w.pg==='demandes'&&w.ser, JSON.stringify(w));
T('Aucune erreur JS', errs.length===0, errs.join(' / '));
await p.waitForTimeout(200); await p.screenshot({path:'v664-cockpit.png'});
console.log(ok+' OK / '+ko+' KO'); await b.close(); })();
