const { chromium, URL_APP } = require('./_socle.cjs');
let ok=0,ko=0; const T=(n,c,d)=>{ if(c){ok++;console.log('  ✓ '+n);} else {ko++;console.log('  ✗ '+n+' — '+(d||''));} };
(async()=>{ const b=await chromium.launch(); const p=await b.newPage({viewport:{width:1500,height:1000}}); const errs=[]; p.on('pageerror',e=>{ if(!/ServiceWorker/.test(e.message)) errs.push(e.message.slice(0,200)); }); p.on('dialog',d=>d.accept());
await p.goto(URL_APP); await p.waitForTimeout(900);
await p.evaluate(()=>{ if(typeof _authGranted==='function')_authGranted(); }); await p.waitForTimeout(1800);
const ev=(f,a)=>p.evaluate(f,a);
await ev(()=>{ window.uiConfirm=(m,fn)=>fn&&fn(); window.confirm=()=>true; window.alert=()=>{}; window.prompt=()=>'test'; window.__toasts=[]; const _t=window.toast; window.toast=function(m){ window.__toasts.push(''+m); try{ return _t&&_t.apply(this,arguments); }catch(e){} }; window.open=()=>({close(){},focus(){},document:{write(){},close(){}}}); try{ ['demandes','agenda','fiscal','formulaire'].forEach(id=>modPauseSet(id,false)); }catch(e){}
  DB.parametres=DB.parametres||{}; DB.demandes=[]; DB.dossiers=[]; DB.clients=[]; DB.parametres.formDrafts=[]; if(typeof formReset==='function') formReset(); state.page='formulaire'; render(); });
// 1. rendu de toutes les variantes
let w=await ev(()=>{ const out=[]; const types=['sas','sasu','sarl','eurl','sci']; const kinds=['siege','dirigeant','denomination','objet','capital','transformation','cession','dissolution','radiation','cloture'];
  formNature('creation'); for(const t of types){ try{ formType(t); const v=document.getElementById('view'); out.push({k:'creation/'+t,len:v.innerHTML.length,inputs:v.querySelectorAll('input,select,textarea').length,undef:(v.innerText.match(/undefined|NaN(?![a-zA-Z])|\[object Object\]/g)||[]).length}); }catch(e){ out.push({k:t,err:e.message}); } }
  formNature('modification'); for(const k of kinds){ try{ formModifKind(k); const v=document.getElementById('view'); out.push({k:'modif/'+k,len:v.innerHTML.length,inputs:v.querySelectorAll('input,select,textarea').length,undef:(v.innerText.match(/undefined|NaN(?![a-zA-Z])|\[object Object\]/g)||[]).length}); }catch(e){ out.push({k,err:e.message}); } }
  formNature('creation'); formType('sas'); return out; });
T('Rendu des 5 formes de création + 10 types de modification sans exception', w.every(x=>!x.err&&x.len>3000&&x.inputs>10), JSON.stringify(w.filter(x=>x.err||x.len<=3000)));
T('Aucun texte cassé dans ces 15 variantes', w.every(x=>!x.undef), JSON.stringify(w.filter(x=>x.undef)));
// 2. liaison de CHAQUE champ du formulaire (création SAS) : saisir → l'objet reçoit la valeur
w=await ev(()=>{ const bad=[]; let n=0; const v=document.getElementById('view'); const F=window.__formData; const get=(o,path)=>path.split('.').reduce((a,k)=>a&&a[k],o);
  const els=[...v.querySelectorAll('input,select,textarea')];
  for(const el of els){ const h=(el.getAttribute('onchange')||'')+' '+(el.getAttribute('oninput')||''); const m=h.match(/formSet\('([^']+)'/); if(!m) continue; const path=m[1]; if(el.readOnly||el.disabled) continue; n++;
    let val; if(el.tagName==='SELECT'){ const opts=[...el.options].filter(o=>o.value); if(!opts.length) continue; val=opts[opts.length-1].value; el.value=val; } else if(el.type==='checkbox'){ el.checked=true; val=true; } else if(el.type==='date'){ val='2026-09-14'; el.value=val; } else if(el.type==='number'){ val='42'; el.value=val; } else { val='T-'+path.replace(/\W/g,'_'); el.value=val; }
    try{ el.dispatchEvent(new Event('input',{bubbles:true})); el.dispatchEvent(new Event('change',{bubbles:true})); }catch(e){ bad.push(path+' evt '+e.message); continue; }
    const got=get(window.__formData,path); const okv=(el.type==='checkbox')?(got===true||got==='on'||got==='true'||got===1):(''+got===''+val);
    if(!okv) bad.push(path+' = '+JSON.stringify(got)+' ≠ '+val); }
  return {n,bad:bad.slice(0,12),nbad:bad.length}; });
T('Chaque champ lié (formSet) enregistre bien sa valeur ('+w.n+' champs testés)', w.nbad===0, w.nbad+' écarts : '+JSON.stringify(w.bad));
// 3. associés & bénéficiaires
w=await ev(()=>{ formReset(); formType('sas'); const o=window.__formData; formAssocAdd(); formAssocAdd(); formAssocSet(0,'nom','LAMBERT'); formAssocSet(0,'prenom','Sophie'); formAssocSet(0,'parts','60'); formAssocSet(1,'nom','LAMBERT'); formAssocSet(1,'prenom','Marc'); formAssocSet(1,'parts','40'); formBenAdd(); formBenSet(0,'nom','Sophie LAMBERT'); formBenSet(0,'detention','60');
  const a=o.associes.length, bn=o.beneficiaires.length; formAssocDel(1); formBenDel(0); return {a,bn,a2:o.associes.length,bn2:o.beneficiaires.length,first:o.associes[0]&&o.associes[0].nom}; });
T('Associés et bénéficiaires : ajout, saisie, suppression cohérents', w.a===2&&w.bn===1&&w.a2===1&&w.bn2===0&&w.first==='LAMBERT', JSON.stringify(w));
// 4. manques + cohérence
w=await ev(()=>{ formReset(); formType('sas'); const m0=formManques().length; const o=window.__formData;
  Object.assign(o,{societe:{denomination:'LOGIS PICARDIE',capital:'5000',objet:'Location de logements',debut:'2026-10-01',regime:'IS'},titres:{nominal:'10',nbTitres:'500'},apports:{numeraire:'5000',nature:'0'},siege:{rue:'14 rue des Jacobins',cp:'80000',ville:'Amiens',type:'domiciliation'},direction:{civilite:'Mme',prenom:'Sophie',nom:'LAMBERT',naissance:'1988-03-12',lieuNaissance:'Amiens',pays:'France',nationalite:'Française',adresse:'14 rue des Jacobins 80000 Amiens',fonction:'Président'},contact:{email:'s.lambert@logis.fr',tel:'0612345678'},dates:{dateActe:'2026-09-14',villeSignature:'Amiens'},depot:{type:'Banque',banque:'Crédit Agricole',montant:'5000',date:'2026-09-10'},associes:[{civilite:'Mme',prenom:'Sophie',nom:'LAMBERT',parts:'300',apport:'3000',naissance:'1988-03-12',lieuNaissance:'Amiens',pays:'France',nationalite:'Française',adresse:'Amiens'},{civilite:'M.',prenom:'Marc',nom:'LAMBERT',parts:'200',apport:'2000',naissance:'1985-07-02',lieuNaissance:'Lille',pays:'France',nationalite:'Française',adresse:'Lille'}]});
  const m1=formManques(); const coh=formCoherence(); const bad=coh.filter(x=>!x.ok).map(x=>x.label||x.msg||JSON.stringify(x));
  o.associes[1].parts='250'; const coh2=formCoherence(); const bad2=coh2.filter(x=>!x.ok).length; o.associes[1].parts='200';
  return {m0,m1:m1.length,m1l:m1.slice(0,8),nCoh:coh.length,bad,bad2}; });
console.log('   manques:',JSON.stringify(w.m1l));
T('Manques : liste non vide sur formulaire vide ('+w.m0+'), réduite une fois renseigné ('+w.m1+')', w.m0>5&&w.m1<w.m0, JSON.stringify(w.m1l));
T('Cohérence : capital 5 000 = 500 titres × 10 = apports = parts → OK ; parts 550/500 → incohérence détectée', w.nCoh>0&&w.bad.length===0&&w.bad2>0, JSON.stringify({bad:w.bad,bad2:w.bad2}));
// 5. brouillons
w=await ev(()=>{ formBrouillon(); const n1=(DB.parametres.formDrafts||[]).length; const lab=(DB.parametres.formDrafts||[])[0]&&(DB.parametres.formDrafts||[])[0].label; formReset(); const empty=!(window.__formData.societe&&window.__formData.societe.denomination); formReprendre(); const back=window.__formData.societe.denomination; const html=formDraftsListHTML(); formBrouillonSuppr((DB.parametres.formDrafts||[])[0].id); const n2=(DB.parametres.formDrafts||[]).length; return {n1,lab,empty,back,html:html.length>50,n2}; });
T('Brouillon : enregistré (nommé), formulaire vidé, repris, listé, supprimé', w.n1===1&&w.lab&&w.empty&&w.back==='LOGIS PICARDIE'&&w.html&&w.n2===0, JSON.stringify(w));
// 6. pré-remplissage depuis une demande (questionnaire public)
const payload=await ev(()=>{ const pay={version:'INFOSv1',dossier:'',libre:true,type:'sas',champs:{denomination:'LOGIS PICARDIE',objet:'Location de logements meublés',ape:'6820A',siege:'14 rue des Jacobins',cp:'80000',ville:'Amiens',capital:'5000',debut:'2026-10-01',fonction:'Président',civilite:'Mme',nom:'LAMBERT',prenom:'Sophie',naissance:'1988-03-12',lieuNaissance:'Amiens',nationalite:'Française',adresse:'14 rue des Jacobins',adrCp:'80000',adrVille:'Amiens',perePrenom:'Jean',pereNom:'LAMBERT',merePrenom:'Marie',mereNom:'DURAND',secu:'288038002104512',telPro:'0612345678',mailPro:'s.lambert@logis-picardie.fr',typePiece:'cni',heberge:'oui',hebergeurNom:'Paul LAMBERT'},associes:[{nom:'LAMBERT',prenom:'Marc',parts:'40',naissance:'1985-07-02',lieuNaissance:'Lille',nationalite:'Française',adresse:'2 rue Haute, 59000 Lille'}],pieces:{cni:['cni.jpg'],domicile:['edf.pdf'],rib:['rib.pdf']},message:'',email:'s.lambert@logis-picardie.fr',tel:'0612345678',ts:Date.now()}; return btoa(unescape(encodeURIComponent(JSON.stringify(pay)))); });
w=await ev((payload)=>{ DB.parametres.mailsImportes=[]; demIngest([{id:'fq1',from:'FormSubmit <noreply@formsubmit.co>',subject:'QUESTIONNAIRE — Sophie LAMBERT — LOGIS PICARDIE — AEM CONSEIL',date:new Date().toISOString(),body:'LAST_INFOS: INFOSv1:'+payload,att:['cni.jpg','edf.pdf','rib.pdf']}]); const d=DB.demandes[0]; formReset(); formPrefillFromDemande(d.id); state.page='formulaire'; render(); const o=window.__formData; return {den:o.societe&&o.societe.denomination,dir:o.direction&&(o.direction.prenom+' '+o.direction.nom),cap:o.societe&&o.societe.capital,ape:o.societe&&o.societe.ape,secu:o.dirx&&o.dirx.secu,mailPro:o.contact&&(o.contact.emailPro||o.contact.email),assoc:(o.associes||[]).length,siege:o.siege&&o.siege.ville,type:o.type,pere:o.dirx&&o.dirx.pereNom}; },payload);
T('Pré-remplissage depuis le questionnaire : société, dirigeant, capital, APE, siège, parents, sécu, mail pro, associés', w.den==='LOGIS PICARDIE'&&/Sophie LAMBERT/.test(w.dir)&&w.cap==='5000'&&w.ape==='6820A'&&w.siege==='Amiens'&&w.secu&&w.mailPro&&w.assoc>=1&&w.pere==='Jean LAMBERT'&&w.type==='sas', JSON.stringify(w));
// 7. création de dossier : gate manques → puis complet → dossier + client + numéros
w=await ev(()=>{ const o=window.__formData; window.__toasts=[]; const n0=DB.dossiers.length; formCreerDossier(false); const gated=DB.dossiers.length===n0; try{ closeModal(); }catch(e){}
  const m=formManques(); // compléter ce qui manque
  Object.assign(o,{titres:{nominal:'10',nbTitres:'500'},apports:{numeraire:'5000',nature:'0'},dates:{dateActe:'2026-09-14',villeSignature:'Amiens'},depot:{type:'Banque',banque:'Crédit Agricole',montant:'5000',date:'2026-09-10'}}); o.societe.regime=o.societe.regime||'IS'; o.societe.objet=o.societe.objet||'Location'; o.societe.debut=o.societe.debut||'2026-10-01'; o.siege=Object.assign({rue:'14 rue des Jacobins',cp:'80000',ville:'Amiens',type:'domiciliation'},o.siege||{}); o.direction=Object.assign({civilite:'Mme',prenom:'Sophie',nom:'LAMBERT',naissance:'1988-03-12',lieuNaissance:'Amiens',pays:'France',nationalite:'Française',adresse:'Amiens',fonction:'Président'},o.direction||{}); o.contact=Object.assign({email:'s@l.fr',tel:'06'},o.contact||{});
  o.associes=[{civilite:'Mme',prenom:'Sophie',nom:'LAMBERT',parts:'300',apport:'3000',naissance:'1988-03-12',lieuNaissance:'Amiens',pays:'France',nationalite:'Française',adresse:'Amiens'},{civilite:'M.',prenom:'Marc',nom:'LAMBERT',parts:'200',apport:'2000',naissance:'1985-07-02',lieuNaissance:'Lille',pays:'France',nationalite:'Française',adresse:'Lille'}];
  const m2=formManques(); const num=formNextDossierNum(); formCreerDossier(false); try{ closeModal(); }catch(e){}
  const dos=DB.dossiers[DB.dossiers.length-1]; return {gated,m:m.length,m2,num,created:DB.dossiers.length-n0,ref:dos&&(dos.numeroDossier||dos.ref),intake:!!(dos&&dos.intake&&dos.intake.societe.denomination==='LOGIS PICARDIE'),secu:!!(dos&&dos.intake&&dos.intake.dirx&&dos.intake.dirx.secu),cliSecu:!!(DB.clients[0]&&DB.clients[0].secu),pere:DB.clients[0]&&DB.clients[0].docVars&&DB.clients[0].docVars.pereNom,client:DB.clients.length,cliNom:DB.clients[0]&&(DB.clients[0].prenom+' '+DB.clients[0].nom),next:formNextDossierNum(),docs:dos&&Object.keys(dos.docs||{}).length,formVide:!(window.__formData.societe&&window.__formData.societe.denomination),toasts:window.__toasts.slice(-3)}; });
T('Création bloquée tant que des champs manquent (modale de contrôle)', w.gated&&w.m>0, JSON.stringify({gated:w.gated,m:w.m}));
T('Formulaire complet → dossier créé (numéro annoncé, intake + n° sécu + filiation conservés, client créé, numéro suivant)', w.m2.length===0&&w.created===1&&w.ref===w.num&&w.intake&&w.client===1&&w.next!==w.num&&w.secu&&w.cliSecu&&w.pere==='Jean LAMBERT', JSON.stringify(w));
// 8. doublon : même dénomination → alerte ; modification sur société existante
w=await ev(()=>{ formReset(); window.__formData.societe={denomination:'LOGIS PICARDIE'}; const dup=formDoublons().length; const html=formDoublonHTML(); formReset(); formNature('modification'); formModifKind('siege'); const o=window.__formData; o.contact={email:'s.lambert@logis.fr',tel:'0612345678'}; o.modif={kind:'siege',societe:{denomination:'LOGIS PICARDIE',forme:'sas',siren:'912456789',rcsVille:'Amiens',siege:'14 rue des Jacobins',cp:'80000',ville:'Amiens'},dates:{acte:'2026-09-14',effet:'2026-10-01',ville:'Amiens'},signataire:{prenom:'Sophie',nom:'LAMBERT'},nouveau:{siege:'3 quai du Canal',cp:'80000',ville:'Amiens'}}; const mq=formManques(); const n0=DB.dossiers.length; formCreerDossier(false); try{ closeModal(); }catch(e){} const dos=DB.dossiers[DB.dossiers.length-1]; return {dup,html:html.length>20,mq:mq,created:DB.dossiers.length-n0,ref:dos&&(dos.numeroDossier||dos.ref),nature:dos&&(dos.nature||dos.formalite||dos.type||''),svc:dos&&(dos.serviceSouhaite||'')}; });
T('Doublon : une société déjà en dossier est signalée', w.dup===1&&w.html, JSON.stringify({dup:w.dup}));
T('Modification statutaire (transfert de siège) : contrôles passés → dossier de modification créé', w.mq.length===0&&w.created===1&&w.ref, JSON.stringify(w));
// 9. SIRET / SIREN hors ligne : pas d'exception
w=await ev(()=>new Promise(res=>{ const r={}; try{ formReset(); window.__formData.societe={siren:'912456789',siret:'91245678900021'}; formSirenLookup&&formSirenLookup(); formSiretLookup&&formSiretLookup(); r.called=true; }catch(e){ r.err=e.message; } setTimeout(()=>res(r),1500); }));
T('Recherche SIREN / SIRET hors ligne : pas d’exception', w.called&&!w.err, JSON.stringify(w));
// 10. fuzz des boutons (création + modification)
w=await ev(()=>{ const bad=[]; let n=0; const skip=/creer|create|supprim|reset|go\(|location|print|logout|deconn|vider/i;
  for(const nat of ['creation','modification']){ formReset(); formNature(nat); const seen=new Set(); for(let pass=0;pass<2;pass++){ const v=document.getElementById('view'); const btns=[...v.querySelectorAll('button')].filter(b=>!b.disabled); for(const bt of btns){ const oc=bt.getAttribute('onclick')||''; const key=nat+'|'+oc+'|'+bt.textContent.trim(); if(seen.has(key)||skip.test(oc)) continue; seen.add(key); n++; try{ bt.click(); }catch(e){ bad.push(key.slice(0,90)+' → '+e.message.slice(0,80)); } try{ closeModal(); }catch(e){} if(state.page!=='formulaire'){ state.page='formulaire'; render(); } } } }
  return {n,bad}; });
T('Boutons du formulaire cliqués sans exception ('+w.n+' boutons)', w.bad.length===0, JSON.stringify(w.bad));
w=await ev(()=>{ let json=''; try{ json=JSON.stringify(DB); }catch(e){ return {err:e.message}; } const ids=DB.dossiers.map(d=>d.id); const refs=DB.dossiers.map(d=>d.numeroDossier||d.ref); return {size:json.length,uniq:new Set(ids).size===ids.length,uniqRef:new Set(refs).size===refs.length,refs}; });
T('Intégrité : base sérialisable, identifiants et numéros de dossier uniques', !w.err&&w.uniq&&w.uniqRef, JSON.stringify(w));
T('Aucune erreur JS pendant l’audit', errs.length===0, errs.join(' | '));
await p.screenshot({path:__dirname+'/formaudit.png'});
console.log(ok+' OK / '+ko+' KO'); await b.close(); process.exit(ko?1:0); })();
