const { chromium, URL_APP } = require('./_socle.cjs');
let ok=0,ko=0; const T=(n,c,d)=>{ if(c){ok++;console.log('  ✓ '+n);} else {ko++;console.log('  ✗ '+n+' — '+(d||''));} };
(async()=>{ const b=await chromium.launch(); const p=await b.newPage({viewport:{width:1500,height:1000}}); const errs=[]; p.on('pageerror',e=>{ if(!/ServiceWorker/.test(e.message)) errs.push(e.message.slice(0,200)); }); p.on('dialog',d=>{ errs.push('DIALOG NATIF: '+d.message()); d.dismiss(); });
await p.goto(URL_APP); await p.waitForTimeout(900);
await p.evaluate(()=>{ try{ localStorage.setItem('marq-nt-seen','1000'); }catch(e){} if(typeof _authGranted==='function')_authGranted(); }); await p.waitForTimeout(2000);
const ev=(f,a)=>p.evaluate(f,a);
await ev(()=>{ const now=Date.now(); const iso=(d)=>new Date(d).toISOString().slice(0,10);
  DB.clients=[{id:'c1',clientType:'entreprise',denomination:'LOGIS PICARDIE',email:'contact@logis.fr'}];
  DB.demandes=[{id:'m1',societe:'BATI NORD',email:'x@y.fr',statut:'Nouvelle',historique:[{d:iso(now),t:'Demande reçue par e-mail'}]},{id:'m2',societe:'ANCIENNE',statut:'Clôturé',dossierId:'d1',historique:[]}];
  DB.dossiers=[{id:'d1',ref:'DOS-1',clientIds:['c1'],statut:'Qualification',wf:{},historique:[{d:iso(now),t:'Pièces reçues'},{d:iso(now-86400000*3),t:'Dossier créé'}],intake:{type:'sas',societe:{denomination:'LOGIS PICARDIE'}}}];
  DB.parametres.edChaine={journal:[{ts:now-60000,step:'Finalisé',ok:true,detail:'Attestations',qui:'Attestation de CA',mode:'automatique'}],edites:{}};
  save(); state.page='cockpit'; render(); });
await p.waitForTimeout(700);
let w=await ev(()=>{ const bell=document.getElementById('nt-bell'); const tb=document.querySelector('.topbar'); const bd=document.getElementById('nt-badge'); return {bell:!!bell, inTop:!!(bell&&tb&&bell.parentNode===tb), beforeRefresh:!!(bell&&bell.nextElementSibling&&bell.nextElementSibling.classList.contains('topbar-refresh')), badge:bd&&!bd.hidden?bd.textContent:'', unread:ntUnread(), items:ntItems().length, kinds:[...new Set(ntItems().map(x=>x.k))].sort().join(), panelHidden:document.getElementById('nt-panel').hidden}; });
T('Cloche dans la barre du haut (avant Actualiser), compteur des non lus (événements + demande à traiter), sources : événements, automatisations, actions à traiter', w.bell&&w.inTop&&w.beforeRefresh&&+w.badge>=3&&w.unread===+w.badge&&w.items>=3&&w.kinds==='auto,evt,todo'&&w.panelHidden, JSON.stringify(w));
await p.click('#nt-bell'); await p.waitForTimeout(200);
w=await ev(()=>{ const pn=document.getElementById('nt-panel'); const t=pn.innerText; return {open:!pn.hidden, rows:pn.querySelectorAll('.nt-row').length, unread:pn.querySelectorAll('.nt-row.unread').length, dem:/1 demande\(s\) à traiter/.test(t), evt:/Pièces reçues/.test(t), auto:/Éditions/.test(t)&&/Finalisé/.test(t), todo:pn.querySelectorAll('.nt-row.todo').length>=1, u:(t.match(/undefined|NaN(?![a-zA-Z])|\[object Object\]/g)||[]).length}; });
T('Panneau ouvert : lignes cliquables (demande à traiter, événements de dossier, action automatique Éditions, action à traiter), aucun texte parasite', w.open&&w.rows>=4&&w.unread>=3&&w.dem&&w.evt&&w.auto&&w.todo&&w.u===0, JSON.stringify(w));
w=await ev(()=>{ const L=window.__ntOpen; const i=L.findIndex(x=>x.k==='evt'&&/Pièces reçues/.test(x.txt)); ntGo(i); return {page:state.page, id:state.dossierId, closed:document.getElementById('nt-panel').hidden}; });
T('Clic sur un événement de dossier → ouvre le Traitement sur ce dossier, panneau refermé', w.page==='espace'&&w.id==='d1'&&w.closed, JSON.stringify(w));
w=await ev(()=>{ ntToggle(); const L=window.__ntOpen; const i=L.findIndex(x=>x.k==='evt'&&/Demande reçue/.test(x.txt)); ntGo(i); return {page:state.page}; });
T('Clic sur un événement de demande → ouvre les Demandes', w.page==='demandes', JSON.stringify(w));
w=await ev(()=>{ ntMarkAll(); const bd=document.getElementById('nt-badge'); return {seen:+localStorage.getItem('marq-nt-seen')>Date.now()-5000, badge:bd.hidden?'':bd.textContent, unreadEvt:ntItems().filter(x=>x.unread).length}; });
T('« Tout marquer lu » : événements lus et persistés ; seule la demande à traiter reste comptée', w.seen&&w.unreadEvt===0&&w.badge==='1', JSON.stringify(w));
w=await ev(()=>{ state.page='cockpit'; render(); toast('Facture envoyée — voir le client','','success',{go:'clients'}); const el=document.getElementById('toast'); const act=el.classList.contains('tst-act'); el.click(); const pg=state.page; toast('Simple message'); const act2=el.classList.contains('tst-act'); return {act,pg,act2}; });
T('Notification éphémère cliquable : clic → page cible ; un message sans action reste non cliquable', w.act&&w.pg==='clients'&&!w.act2, JSON.stringify(w));
w=await ev(()=>{ state.page='cockpit'; render(); const al=document.querySelector('.dash-alert'); if(!al) return {none:true}; let clicked=false; const b=al.querySelector('button,a'); const _c=b.onclick; b.onclick=function(ev){ clicked=true; ev&&ev.preventDefault&&ev.preventDefault(); }; al.click(); b.onclick=_c; return {cursor:getComputedStyle(al).cursor, clicked}; });
T('Bandeau de sauvegarde : toute la surface est cliquable et déclenche son action', w.none||(w.cursor==='pointer'&&w.clicked), JSON.stringify(w));
w=await ev(()=>{ const g=(el)=>{ const cs=getComputedStyle(el); return cs.backgroundColor+'|'+cs.color; }; const mk=(cls)=>{ const b=document.createElement('button'); b.className='btn '+cls; b.textContent='x'; document.getElementById('view').appendChild(b); const r=g(b); b.remove(); return r; }; const r={pri:mk('btn-pri'),sec:mk(''),ghost:mk('btn-ghost'),danger:mk('btn-danger')}; uiConfirm('t',function(){},{danger:false}); r.modalPri=g(document.querySelector('#ov-f .btn-pri')); r.modalGhost=g(document.querySelector('#ov-f .btn-ghost')); closeModal(); return r; });
T('Quatre rôles distincts : principal blanc / secondaire gris foncé / discret transparent / danger rouge sombre — identiques dans les modales', w.pri.startsWith('rgb(241, 241, 244)')&&w.sec.startsWith('rgb(29, 29, 34)')&&w.ghost.startsWith('rgba(0, 0, 0, 0)')&&w.danger.startsWith('rgb(42, 21, 21)')&&w.modalPri===w.pri&&w.modalGhost===w.ghost, JSON.stringify(w));
T('Aucune erreur JS ni boîte native', errs.length===0, errs.join(' / '));
await ev(()=>{ state.page='cockpit'; render(); ntToggle(); }); await p.waitForTimeout(400); await p.screenshot({path:'v674-notifs.png'});
console.log(ok+' OK / '+ko+' KO'); await b.close(); })();
