const { chromium, URL_APP } = require('./_socle.cjs');
let ok=0,ko=0; const T=(n,c,d)=>{ if(c){ok++;console.log('  ✓ '+n);} else {ko++;console.log('  ✗ '+n+' — '+(d||''));} };
(async()=>{ const b=await chromium.launch(); const p=await b.newPage({viewport:{width:1500,height:1000}}); const errs=[]; p.on('pageerror',e=>{ if(!/ServiceWorker|Test boom|Test rejet|load https/.test(e.message)) errs.push(e.message.slice(0,200)); }); p.on('dialog',d=>{ errs.push('DIALOG NATIF: '+d.message()); d.dismiss(); });
await p.goto(URL_APP); await p.waitForTimeout(900);
await p.evaluate(()=>{ if(typeof _authGranted==='function')_authGranted(); }); await p.waitForTimeout(2000);
const ev=(f,a)=>p.evaluate(f,a);
await ev(()=>{ window.__toasts=[]; const _t=window.toast; window.toast=function(m){ window.__toasts.push(''+m); try{ return _t.apply(this,arguments); }catch(e){} }; DB.parametres.incidents=[]; save(); state.page='cockpit'; render(); setTimeout(function(){ throw new Error('Test boom'); },10); });
await p.waitForTimeout(400);
let w=await ev(()=>({t:window.__toasts.slice(-1)[0], j:DB.parametres.incidents[0], n:DB.parametres.incidents.length, act:document.getElementById('toast').classList.contains('tst-act')}));
T('Erreur JavaScript non rattrapée → message clair en français (action non aboutie + marche à suivre), consignée dans le journal avec la page, notification cliquable', /Action non aboutie/.test(w.t)&&/Rechargez la page/.test(w.t)&&w.n===1&&w.j.msg==='Test boom'&&w.j.page==='cockpit'&&w.act, JSON.stringify(w));
await ev(()=>{ Promise.reject(new Error('load https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js')); }); await p.waitForTimeout(300);
w=await ev(()=>({t:window.__toasts.slice(-1)[0], k:DB.parametres.incidents[0].kind}));
T('Promesse rejetée (bibliothèque PDF non chargée) → « Connexion requise » avec explication', /Connexion requise/.test(w.t)&&w.k==='reseau', JSON.stringify(w));
w=await ev(()=>{ window.__toasts=[]; const _o=window.open; const stub=function(){ return null; }; /* simule le blocage : on remplace l'original sous le garde */ const guard=window.open; window.open=function(){ window.__popupBlockedAt=Date.now(); return guard.__nt4?null:null; }; DB.editionsLibres=[{id:'e1',k:'attca',titre:'Attestation test',data:{},ts:Date.now(),updated:Date.now()}]; let threw=false; try{ edLibPdf('e1'); }catch(e){ threw=true; } window.open=guard; return {t:window.__toasts.join(' | '), threw}; });
T('Fenêtre pop-up bloquée à l’export PDF → message « Autorisez les fenêtres pop-up », aucune exception', /pop-up/.test(w.t)&&!w.threw, JSON.stringify(w));
w=await ev(()=>{ window.__toasts=[]; const real=window.open; /* garde réel : on force l’original à renvoyer null */ const desc=Object.getOwnPropertyDescriptor(window,'open'); window.open=function(){ return null; }; window.open.__nt4=1; /* appel direct du garde d’origine impossible : on vérifie la détection via incidentSignaler */ window.open=real; try{ const nulls=(function(){ const o=window.open; let r; window.__forceNull=true; r=null; return r; })(); }catch(e){} incidentSignaler(new TypeError("Cannot read properties of null (reading 'document')"),'test'); return {t:window.__toasts.slice(-1)[0], k:DB.parametres.incidents[0].kind}; });
T('Erreur typique d’une fenêtre bloquée non contrôlée → reconnue et expliquée comme « Fenêtre bloquée »', /Fenêtre bloquée/.test(w.t)&&w.k==='popup', JSON.stringify(w));
await p.waitForTimeout(1600); w=await ev(()=>{ window.__toasts=[]; incidentSignaler(new Error('QuotaExceededError: storage full'),'test'); return {t:window.__toasts.slice(-1)[0]}; });
T('Stockage saturé → « Stockage plein » avec la marche à suivre (sauvegarde puis nettoyage)', /Stockage plein/.test(w.t)&&/sauvegarde/i.test(w.t), JSON.stringify(w));
w=await ev(()=>{ state.page='params'; render(); const v=document.getElementById('view'); const c=v.querySelector('.inc-card'); const t=c?c.innerText:''; return {card:!!c, n:c?c.querySelectorAll('.inc-row').length:0, boom:/Test boom/.test(t), titres:/Action non aboutie/.test(t)&&/Connexion requise/.test(t)&&/Stockage plein/.test(t), copier:/Copier le détail/.test(t), u:(t.match(/undefined|NaN(?![a-zA-Z])|\[object Object\]/g)||[]).length}; });
T('Paramètres : carte « Journal des incidents » listant les incidents avec date, page, explication, détail technique et bouton Copier', w.card&&w.n>=4&&w.boom&&w.titres&&w.copier&&w.u===0, JSON.stringify(w));
w=await ev(()=>{ ntToggle(); const pn=document.getElementById('nt-panel'); const t=pn.innerText; const ko=pn.querySelectorAll('.nt-ic.ko').length; const L=window.__ntOpen; const i=L.findIndex(x=>/Incident/.test(x.titre)); ntGo(i); return {inc:/Incident — Action non aboutie/.test(t), ko, page:state.page}; });
T('Centre de notifications : les incidents apparaissent (marqués en rouge) et mènent aux Paramètres', w.inc&&w.ko>=3&&w.page==='params', JSON.stringify(w));
w=await ev(()=>{ incidentsVider(); return {n:DB.parametres.incidents.length, empty:/Aucune action n.a échoué/.test(document.querySelector('#view .inc-card').innerText)}; });
T('« Vider » remet le journal à zéro avec un état vide explicite', w.n===0&&w.empty, JSON.stringify(w));
T('Aucune erreur JS parasite ni boîte native', errs.length===0, errs.join(' / '));
await ev(()=>{ incidentSignaler(new Error('load https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js'),'test'); state.page='params'; render(); window.scrollTo(0,document.body.scrollHeight); }); await p.waitForTimeout(400); await p.screenshot({path:'v675-incidents.png'});
console.log(ok+' OK / '+ko+' KO'); await b.close(); })();
