const { chromium, URL_APP } = require('./_socle.cjs');
let ok=0,ko=0; const T=(n,c,d)=>{ if(c){ok++;console.log('  ✓ '+n);} else {ko++;console.log('  ✗ '+n+' — '+(d||''));} };
(async()=>{ const b=await chromium.launch(); const p=await b.newPage({viewport:{width:1500,height:1000}}); const errs=[]; p.on('pageerror',e=>{ if(!/ServiceWorker/.test(e.message)) errs.push(e.message.slice(0,200)); }); p.on('dialog',d=>d.accept());
await p.goto(URL_APP); await p.waitForTimeout(900);
await p.evaluate(()=>{ if(typeof _authGranted==='function')_authGranted(); }); await p.waitForTimeout(1800);
const ev=(f,a)=>p.evaluate(f,a);
await ev(()=>{ window.uiConfirm=(m,fn)=>fn&&fn(); window.confirm=()=>true; window.alert=()=>{}; window.prompt=()=>'test'; window.__toasts=[]; const _t=window.toast; window.toast=function(m){ window.__toasts.push(''+m); try{ return _t&&_t.apply(this,arguments); }catch(e){} }; window.open=()=>({close(){},focus(){},document:{write(){},close(){}}}); try{ ['demandes','agenda','fiscal','formulaire','espace'].forEach(id=>modPauseSet(id,false)); }catch(e){}
  DB.demandes=[]; DB.dossiers=[]; DB.clients=[]; DB.factures=DB.factures||[]; DB.parametres.formDrafts=[];
  // fabrique de dossiers complets via le Formulaire
  window.__mk=function(type,extra){ formReset(); formNature('creation'); formType(type); const o=window.__formData; const den=(extra&&extra.den)||('SOC '+type.toUpperCase());
    Object.assign(o,{societe:{denomination:den,capital:'5000',objet:'Location de logements meublés',debut:'2026-10-01',regime:'IS'},titres:{nominal:'10',nbTitres:'500'},apports:{numeraire:'5000',nature:'0'},siege:{rue:'14 rue des Jacobins',cp:'80000',ville:'Amiens',type:'domiciliation'},direction:{civilite:'Mme',prenom:'Sophie',nom:'LAMBERT',naissance:'1988-03-12',lieuNaissance:'Amiens',pays:'France',nationalite:'Française',adresse:'14 rue des Jacobins 80000 Amiens',fonction:''},dirx:{pereNom:'Jean LAMBERT',mereNom:'Marie DURAND',secu:'288038002104512',typePiece:'cni'},contact:{email:'s.lambert@logis.fr',tel:'0612345678'},dates:{dateActe:'2026-09-14',villeSignature:'Amiens'},depot:{type:'Banque',banque:'Crédit Agricole',montant:'5000',date:'2026-09-10'},
      associes:(type==='sasu'||type==='eurl')?[{civilite:'Mme',prenom:'Sophie',nom:'LAMBERT',parts:'500',apport:'5000',naissance:'1988-03-12',lieuNaissance:'Amiens',pays:'France',nationalite:'Française',adresse:'Amiens'}]:[{civilite:'Mme',prenom:'Sophie',nom:'LAMBERT',parts:'300',apport:'3000',naissance:'1988-03-12',lieuNaissance:'Amiens',pays:'France',nationalite:'Française',adresse:'Amiens'},{civilite:'M.',prenom:'Marc',nom:'LAMBERT',parts:'200',apport:'2000',naissance:'1985-07-02',lieuNaissance:'Lille',pays:'France',nationalite:'Française',adresse:'Lille'}]});
    const n0=DB.dossiers.length; const mq=formManques(); formCreerDossier(false); try{ closeModal(); }catch(e){} const d=DB.dossiers[0]; return {ok:DB.dossiers.length===n0+1,mq,id:d&&d.id,ref:d&&(d.numeroDossier||d.ref)}; };
  window.__mkModif=function(kind){ formReset(); formNature('modification'); formModifKind(kind); const o=window.__formData; o.contact={email:'eric@garage-dupont.fr',tel:'0611223344'}; o.modif={kind,societe:{denomination:'GARAGE DUPONT',forme:'sarl',siren:'812345678',rcsVille:'Amiens',siege:'5 rue Neuve',cp:'80000',ville:'Amiens'},dates:{acte:'2026-09-14',effet:'2026-10-01',ville:'Amiens'},signataire:{prenom:'Éric',nom:'DUPONT'},nouveau:{siege:'3 quai du Canal',cp:'80000',ville:'Amiens',prenom:'Paul',nom:'DUPONT',naissance:'1990-01-01',adresse:'Amiens',denomination:'GARAGE DUPONT & FILS',objet:'Réparation automobile',capital:'20000',formeNouvelle:'sas',cedant:'Éric DUPONT',cessionnaire:'Paul DUPONT',nbTitres:'100',prix:'10000',liquidateur:'Éric DUPONT',siegeLiquidation:'Amiens',dateClotureLiq:'2026-12-31',ancienneCloture:'31/12',nouvelleCloture:'30/06'}}; const n0=DB.dossiers.length; const mq=formManques(); formCreerDossier(false); try{ closeModal(); }catch(e){} const d=DB.dossiers[0]; return {ok:DB.dossiers.length===n0+1,mq,id:d&&d.id}; };
});
// 1. création de dossiers de chaque forme + modification de chaque type
let w=await ev(()=>{ const out={}; ['sas','sasu','sarl','eurl','sci'].forEach(t=>{ out[t]=window.__mk(t); }); ['siege','dirigeant','denomination','objet','capital','transformation','cession','dissolution','radiation','cloture'].forEach(k=>{ out['m-'+k]=window.__mkModif(k); }); return out; });
T('15 dossiers créés (5 formes de création + 10 modifications) sans manque bloquant', Object.values(w).every(x=>x.ok&&x.mq.length===0), JSON.stringify(Object.entries(w).filter(([k,x])=>!x.ok||x.mq.length).map(([k,x])=>k+':'+JSON.stringify(x.mq))));
// 2. rendu de chaque onglet pour chaque dossier
w=await ev(()=>{ const out=[]; const tabs=['demande','pieces','actes','attestations','immatriculation','cloture']; for(const d of DB.dossiers){ for(const t of tabs){ try{ state.page='espace'; state.espaceDossier=d.id; state.espTab=t; if(d.wf) delete d.wf; render(); const v=document.getElementById('view'); const txt=v.innerText; const u=(txt.match(/undefined|NaN(?![a-zA-Z])|\[object Object\]|\{\{[^}]*\}\}/g)||[]); if(u.length||v.innerHTML.length<3000) out.push({d:d.numeroDossier||d.ref,t,len:v.innerHTML.length,u:u.slice(0,3)}); }catch(e){ out.push({d:d.numeroDossier||d.ref,t,err:e.message}); } } } return out; });
T('6 onglets × 15 dossiers rendus sans exception ni texte cassé (90 vues)', w.length===0, JSON.stringify(w.slice(0,6)));
// 3. actes requis et rendus pour chaque dossier
w=await ev(()=>{ const out=[]; for(const d of DB.dossiers){ let req=[]; try{ req=espDocsRequis(d); }catch(e){ out.push({d:d.ref,err:'req '+e.message}); continue; } if(!req.length){ out.push({d:d.numeroDossier||d.ref,svc:d.serviceSouhaite,err:'aucun acte requis'}); continue; } try{ docGenAll(d.id); }catch(e){ out.push({d:d.ref,err:'gen '+e.message}); } for(const dc of req){ let h=''; try{ h=espDocRender(d,dc.k); }catch(e){ out.push({d:d.numeroDossier||d.ref,k:dc.k,err:e.message}); continue; } const txt=(''+h).replace(/<[^>]+>/g,' ').replace(/\s+/g,' '); const broken=(txt.match(/undefined|NaN(?![a-z])|\[object Object\]|\{\{[^}]*\}\}/g)||[]); if(broken.length||txt.length<300) out.push({d:d.numeroDossier||d.ref,k:dc.k,len:txt.length,broken:broken.slice(0,3)}); } } return {n:DB.dossiers.reduce((a,d)=>a+espDocsRequis(d).length,0),bad:out}; });
T('Actes de tous les dossiers générés et rendus avec un contenu réel ('+w.n+' actes)', w.bad.length===0, JSON.stringify(w.bad.slice(0,8)));
// 4. verrous : validation impossible sans les prérequis, à chaque étape
w=await ev(()=>{ const d=DB.dossiers.find(x=>x.intake&&x.intake.type==='sas'); window.__sasId=d.id; const id=d.id; delete d.wf; const r={}; const wf=()=>d.wf||{};
  window.__toasts=[]; trwValider(id,'pieces'); r.piecesSansDemande=!wf().pieces&&window.__toasts.length>0;
  window.__toasts=[]; trwValider(id,'demande'); r.demande=!!wf().demande;
  window.__toasts=[]; trwValider(id,'pieces'); r.piecesSansCert=!wf().pieces&&/pièce|certif|vide/i.test(window.__toasts.join(' '));
  const L=enregPieces(d); L.forEach(pc=>{ if(pc.origine==='client') enregPieceToggle(id,pc.k,true); }); const ks=[...new Set(e2Pieces(d).map(a=>demAttCat(a).key))]; r.nbPieces=ks.length;
  window.__toasts=[]; trwValider(id,'pieces'); r.piecesApresPieces=!!wf().pieces; r.tPieces=window.__toasts.slice(-1)[0];
  return r; });
console.log('   verrous 1:',JSON.stringify(w));
T('Verrou ordre : « Pièces » refusée avant « Demande » ; « Demande » validée (demandeur identifié)', w.piecesSansDemande&&w.demande, JSON.stringify(w));
T('Verrou pièces : sans pièce certifiée, l’étape « Pièces » est refusée avec un message', w.piecesSansCert, JSON.stringify(w));
// certifier puis valider, puis verrous actes / attestations / immat / clôture
w=await ev(()=>{ const d=DB.dossiers.find(x=>x.id===window.__sasId); const id=d.id; const r={}; const wf=()=>d.wf||{};
  // ce dossier vient du formulaire : aucune pièce jointe → on en crée via attachments
  d.attachments=d.attachments||[]; if(!d.attachments.length){ d.attachments.push({name:'cni-lambert.jpg',msgId:'x'},{name:'edf-domicile.pdf',msgId:'x'},{name:'rib.pdf',msgId:'x'}); }
  const ks=[...new Set(e2Pieces(d).map(a=>demAttCat(a).key))]; ks.forEach(k=>{ try{ e3Certifier(id,k); }catch(e){ r['cert-'+k]=e.message; } }); r.cert=ks;
  window.__toasts=[]; trwValider(id,'pieces'); r.pieces=!!wf().pieces; r.tp=window.__toasts.slice(-1)[0];
  window.__toasts=[]; trwValider(id,'actes'); r.actesSansSign=!wf().actes; r.ta=window.__toasts.slice(-1)[0];
  docGenAll(id); docApproveAll(id); window.__toasts=[]; trwValider(id,'actes'); r.actesSansSign2=!wf().actes; a3ToutSigner(id); window.__toasts=[]; trwValider(id,'actes'); r.actes=!!wf().actes;
  window.__toasts=[]; trwValider(id,'attestations'); r.attSansFichier=!wf().attestations; r.tatt=window.__toasts.slice(-1)[0];
  d.attest=d.attest||{}; ['capital','annonce'].forEach(t=>{ d.attest[t]=d.attest[t]||{}; d.attest[t].fichier={name:'att-'+t+'.pdf',ts:Date.now()}; at4Valider(id,t); }); window.__toasts=[]; trwValider(id,'attestations'); r.att=!!wf().attestations;
  window.__toasts=[]; trwValider(id,'immatriculation'); r.immSansKbis=!wf().immatriculation; d.immat=d.immat||{}; d.immat.kbis={name:'kbis.pdf',ts:Date.now()}; window.__toasts=[]; trwValider(id,'immatriculation'); r.immSansVerif=!wf().immatriculation; im5Valider(id); trwValider(id,'immatriculation'); r.imm=!!wf().immatriculation;
  window.__toasts=[]; trwValider(id,'cloture'); r.cloSansClot=!wf().cloture; r.ctl0=cl6Controles(d).map(x=>x.l+':'+(x.ok?1:0)); window.__toasts=[]; const _uc=window.uiConfirm; window.uiConfirm=(m,fn)=>{ r.confirmMsg=(''+m).slice(0,80); }; cl6Cloturer(id); window.uiConfirm=_uc; r.clotRefusee=d.statut!=='Clôturé'&&/reste à accomplir/i.test(r.confirmMsg||''); r.tc=window.__toasts.slice(-1)[0];
  const c=(d.cloture=d.cloture||{}); cl6Facturer(id); try{ closeModal(); }catch(e){} c.remis=Date.now(); c.remisA='s.lambert@logis.fr'; cl6Compta(id); r.ctl1=cl6Controles(d).map(x=>x.l+':'+(x.ok?1:0)); cl6Cloturer(id); r.statut=d.statut; trwValider(id,'cloture'); r.clo=!!wf().cloture; r.facture=!!c.factureId;
  return r; });
console.log('   verrous 2:',JSON.stringify(w));
T('Pièces certifiées ('+(w.cert||[]).length+') → étape « Pièces » validée', w.pieces, JSON.stringify({cert:w.cert,tp:w.tp}));
T('Verrou actes : refusée sans actes générés, refusée approuvés-non-signés, acceptée une fois tout signé', w.actesSansSign&&w.actesSansSign2&&w.actes, JSON.stringify({a:w.actesSansSign,b:w.actesSansSign2,c:w.actes,ta:w.ta}));
T('Verrou attestations : refusée sans fichiers vérifiés, acceptée après vérification capital + annonce', w.attSansFichier&&w.att, JSON.stringify({a:w.attSansFichier,b:w.att,t:w.tatt}));
T('Verrou immatriculation : refusée sans K-bis, refusée K-bis non vérifié, acceptée après vérification', w.immSansKbis&&w.immSansVerif&&w.imm, JSON.stringify({a:w.immSansKbis,b:w.immSansVerif,c:w.imm}));
T('Verrou clôture : demande confirmation tant que facture/remise/compta manquent, puis clôturée (facture créée)', w.cloSansClot&&w.clotRefusee&&w.ctl1.every(x=>/:1$/.test(x))&&w.statut==='Clôturé'&&w.clo&&w.facture, JSON.stringify({ctl0:w.ctl0,ctl1:w.ctl1,statut:w.statut,tc:w.tc}));
// 5. révocation / réouverture / décertification
w=await ev(()=>{ const d=DB.dossiers.find(x=>x.id===window.__sasId); const id=d.id; const r={}; cl6Rouvrir(id); r.rouvert=d.statut!=='Clôturé'; trwRevoquer(id,'actes'); r.wfApres=Object.keys(d.wf||{}); r.actesRevoques=!d.wf.actes&&!d.wf.attestations&&!d.wf.immatriculation&&!d.wf.cloture&&!!d.wf.pieces;
  const k=[...new Set(e2Pieces(d).map(a=>demAttCat(a).key))][0]; e3Decertifier(id,k); trwRevoquer(id,'pieces'); window.__toasts=[]; trwValider(id,'pieces'); r.piecesRefuseeApresDecert=!d.wf.pieces; e3Certifier(id,k); trwValider(id,'pieces'); r.pieces2=!!d.wf.pieces;
  at4Retirer(id,'capital'); r.attRetiree=!(d.attest&&d.attest.capital&&d.attest.capital.fichier); im5Retirer(id,'kbis'); r.kbisRetire=!(d.immat&&d.immat.kbis);
  return r; });
T('Réouverture, révocation en cascade (actes → clôture), décertification bloque à nouveau, retrait attestation / K-bis', w.rouvert&&w.actesRevoques&&w.piecesRefuseeApresDecert&&w.pieces2&&w.attRetiree&&w.kbisRetire, JSON.stringify(w));
// 6. parcours complet sur une SARL, une SCI et une modification (transfert de siège)
w=await ev(()=>{ const out={}; const run=(d)=>{ const id=d.id; const r={}; delete d.wf; try{ trwValider(id,'demande'); d.attachments=d.attachments||[]; if(!d.attachments.length) d.attachments.push({name:'cni-dirigeant.jpg'},{name:'facture-edf-domicile.pdf'},{name:'rib.pdf'}); enregPieces(d).forEach(pc=>{ if(pc.origine==='client') enregPieceToggle(id,pc.k,true); }); [...new Set(e2Pieces(d).map(a=>demAttCat(a).key))].forEach(k=>e3Certifier(id,k)); trwValider(id,'pieces'); docGenAll(id); docApproveAll(id); a3ToutSigner(id); trwValider(id,'actes'); d.attest=d.attest||{}; ['capital','annonce'].forEach(t=>{ d.attest[t]=d.attest[t]||{}; d.attest[t].fichier={name:t+'.pdf',ts:Date.now()}; at4Valider(id,t); }); trwValider(id,'attestations'); d.immat=d.immat||{}; d.immat.kbis={name:'kbis.pdf',ts:Date.now()}; im5Valider(id); trwValider(id,'immatriculation'); const c=(d.cloture=d.cloture||{}); cl6Facturer(id); try{ closeModal(); }catch(e){} c.remis=Date.now(); c.remisA='x@y.fr'; cl6Compta(id); cl6Cloturer(id); trwValider(id,'cloture'); }catch(e){ r.err=e.message; } r.wf=Object.keys(d.wf||{}).filter(k=>!/^__/.test(k)).length; r.statut=d.statut; return r; };
  out.sarl=run(DB.dossiers.find(x=>x.intake&&x.intake.type==='sarl')); out.sci=run(DB.dossiers.find(x=>x.intake&&x.intake.type==='sci')); out.modif=run(DB.dossiers.find(x=>x.nature==='modification'||/modif|siège|siege|transfert/i.test((x.serviceSouhaite||'')+(x.formalite||'')+(x.formaliteType||'')))); return out; });
console.log('   parcours:',JSON.stringify(w));
T('Parcours complet (6 étapes) sur une SARL, une SCI et une modification statutaire', Object.values(w).every(x=>x&&!x.err&&x.wf===6&&x.statut==='Clôturé'), JSON.stringify(w));
// 7. archivage / suppression / suivi client / dépôt INPI / attestation
w=await ev(()=>{ const r={}; const d=DB.dossiers[1]; const id=d.id; state.espaceDossier=id; for(const f of ['espSuiviEnvoyer','espDepotInpi','espAttestation','espFicheTechnique','espDocsModal','espMailCard','espPiecesCard','espTraitementCard','espInpiSuiviCard','espStatutsCard']){ try{ const x=window[f](f==='espMailCard'||f==='espPiecesCard'||f==='espTraitementCard'||f==='espInpiSuiviCard'||f==='espStatutsCard'?d:id); r[f]=typeof x==='string'?'html '+x.length:'ok'; }catch(e){ r[f]='ERR '+e.message; } try{ closeModal(); }catch(e){} }
  const n=DB.dossiers.length; espArchiverDossier(id); r.arch=!!d.archived; espDesarchiver(id); r.desarch=!d.archived; const d2=DB.dossiers[2]; espSupprimerDossier(d2.id); r.suppr=DB.dossiers.length===n-1&&!DB.dossiers.some(x=>x.id===d2.id); return r; });
T('Suivi client, dépôt INPI, attestation, fiche technique, modale des actes, cartes : sans exception', Object.values(w).filter(v=>typeof v==='string').every(v=>!/ERR/.test(v)), JSON.stringify(w));
T('Archivage / désarchivage / suppression d’un dossier', w.arch&&w.desarch&&w.suppr, JSON.stringify({a:w.arch,b:w.desarch,c:w.suppr}));
// 8. fuzz des boutons de chaque onglet (dossier en cours)
w=await ev(()=>{ const bad=[]; let n=0; const skip=/supprim|archiv|go\(|location|print|logout|deconn|reset|vider|cloturer|revoquer|trwValider/i; const d=DB.dossiers[3]; state.page='espace'; state.espaceDossier=d.id;
  for(const t of ['demande','pieces','actes','attestations','immatriculation','cloture']){ state.espTab=t; render(); const seen=new Set(); for(let pass=0;pass<2;pass++){ const v=document.getElementById('view'); const btns=[...v.querySelectorAll('button')].filter(b=>!b.disabled); for(const bt of btns){ const oc=bt.getAttribute('onclick')||''; const key=t+'|'+oc+'|'+bt.textContent.trim(); if(seen.has(key)||skip.test(oc)||skip.test(bt.textContent)) continue; seen.add(key); n++; try{ bt.click(); }catch(e){ bad.push(key.slice(0,90)+' → '+e.message.slice(0,80)); } try{ closeModal(); }catch(e){} document.querySelectorAll('.esp-ed-ov,.ed-ov').forEach(x=>x.remove()); if(state.page!=='espace'){ state.page='espace'; } state.espaceDossier=d.id; state.espTab=t; render(); } } }
  return {n,bad}; });
T('Boutons des 6 onglets cliqués sans exception ('+w.n+' boutons)', w.bad.length===0, JSON.stringify(w.bad.slice(0,6)));
w=await ev(()=>{ let json=''; try{ json=JSON.stringify(DB); }catch(e){ return {err:e.message}; } const ids=DB.dossiers.map(d=>d.id); const refs=DB.dossiers.map(d=>d.numeroDossier||d.ref); return {size:json.length,uniq:new Set(ids).size===ids.length,uniqRef:new Set(refs).size===refs.length,n:DB.dossiers.length,fact:(DB.factures||[]).length}; });
T('Intégrité : base sérialisable, identifiants et numéros uniques', !w.err&&w.uniq&&w.uniqRef, JSON.stringify(w));
T('Aucune erreur JS pendant l’audit', errs.length===0, errs.join(' | '));
await p.screenshot({path:__dirname+'/traudit.png'});
console.log(ok+' OK / '+ko+' KO'); await b.close(); process.exit(ko?1:0); })();
